version: '3'
services:
    users-statics:
        build: ./users-statics
        volumes:
            - ./users-statics:/usr/src/app
        ports:
            - 5001:5000
        networks:
            - users-network
        depends_on:
            - users-api
            
    users-api:
        build: ./users-api
        volumes:
            - ./users-api:/usr/src/app
        ports:
            - 5002:3000
        networks:
            - users-network

    users-db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: SecureP@ssw0rd
        ports:
            - 5003:5432
        networks:
            - users-network

networks:
    users-network:
        driver: bridge