version: '3'
services: 
    statics-server:
        build: ./statics-server
        volumes:
            - ./statics-server:/usr/src/app
        ports:
            - 5001:5000

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: SecureP@ssw0rd

    api:
        build: ./api-server
        volumes:
            - ./api-server:/usr/src/app
        ports:
            - 5002:5000
        links:
            - db:database