version: '3'
services:
    users-statics:
        build: ./users-statics
        volumes:
            - ./users-statics:/usr/src/app
        ports:
            - 3000:3000
        networks:
            - users-network
        depends_on:
            - users-api
            
    users-api:
        build: ./users-api
        volumes:
            - ./users-api:/usr/src/app
        ports:
            - 5000:5000
        networks:
            - users-network

    users-db:
        image: postgres
        volumes:
            - ./users-db:/var/lib/postgresql/
        restart: always
        environment:
            POSTGRES_USER: users
            POSTGRES_PASSWORD: SecurePassw0rd
        ports:
            - 5432:5432
        networks:
            - users-network

    users-test:
        build: ./users-test
        volumes:
            - ./users-test:/usr/src/app
        networks:
            - users-network
        depends_on:
            - users-statics

networks:
    users-network:
        driver: bridge