version: '3'
services: 
    statics-server:
        build: ./statics-server
        volumes:
            - ./statics-server:/usr/src/app
        ports:
            - 5001:5000
        links:
            - db:database

    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: SecureP@ssw0rd